import json

from django.db import models

# Create your models here.
import mongoengine
class lrb(mongoengine.Document):
    TOTALOPERATEREVE = mongoengine.FloatField(max_length=30)
    OPERATEREVE = mongoengine.FloatField(max_length=30)
    TOTALOPERATEEXP = mongoengine.FloatField(max_length=30)
    OPERATEEXP = mongoengine.FloatField(max_length=30)
    RDEXP = mongoengine.FloatField(max_length=30)
    OPERATETAX = mongoengine.FloatField(max_length=30)
    SALEEXP = mongoengine.FloatField(max_length=30)
    MANAGEEXP = mongoengine.FloatField(max_length=30)
    FINANCEEXP = mongoengine.FloatField(max_length=30)
    ASSETDEVALUELOSS = mongoengine.FloatField(max_length=30)
    FVALUEINCOME = mongoengine.FloatField(max_length=30)
    INVESTINCOME = mongoengine.FloatField(max_length=30)
    OPERATEPROFIT = mongoengine.FloatField(max_length=30)
    RDEXP = mongoengine.FloatField(max_length=30)
    NONOPERATEREVE = mongoengine.FloatField(max_length=30)
    NONOPERATEEXP = mongoengine.FloatField(max_length=30)
    REPORTDATE = mongoengine.StringField(max_length=30)
    STOCKNAME = mongoengine.StringField(max_length=30)

class code(mongoengine.Document):
    area = mongoengine.StringField(max_length=3)
    name = mongoengine.StringField(max_length=20)
    code = mongoengine.StringField(max_length=10)

class codep(mongoengine.Document):
    area = mongoengine.StringField(max_length=3)
    name = mongoengine.StringField(max_length=20)

class xjllb(mongoengine.Document):
    REPORTDATE = mongoengine.StringField(max_length=30)
    STOCKNAME = mongoengine.StringField(max_length=30)
    SALEGOODSSERVICEREC = mongoengine.FloatField(max_length=30)
    TAXRETURNREC = mongoengine.FloatField(max_length=30)
    OTHEROPERATEREC = mongoengine.FloatField(max_length=30)
    SUMOPERATEFLOWIN = mongoengine.FloatField(max_length=30)
    BUYGOODSSERVICEPAY = mongoengine.FloatField(max_length=30)
    EMPLOYEEPAY = mongoengine.FloatField(max_length=30)
    TAXPAY = mongoengine.FloatField(max_length=30)
    OTHEROPERATEPAY = mongoengine.FloatField(max_length=30)
    SUMOPERATEFLOWOUT = mongoengine.FloatField(max_length=30)
    NETOPERATECASHFLOW = mongoengine.FloatField(max_length=30)
    DISPOSALINVREC = mongoengine.FloatField(max_length=30)
    INVINCOMEREC = mongoengine.FloatField(max_length=30)
    DISPFILASSETREC = mongoengine.FloatField(max_length=30)
    OTHERINVREC = mongoengine.FloatField(max_length=30)
    SUMINVFLOWIN = mongoengine.FloatField(max_length=30)
    BUYFILASSETPAY = mongoengine.FloatField(max_length=30)
    INVPAY = mongoengine.FloatField(max_length=30)
    OTHERINVPAY = mongoengine.FloatField(max_length=30)
    SUMINVFLOWOUT = mongoengine.FloatField(max_length=30)
    NETINVCASHFLOW = mongoengine.FloatField(max_length=30)
    SUBSIDIARYACCEPT = mongoengine.FloatField(max_length=30)
    LOANREC = mongoengine.FloatField(max_length=30)
    OTHERFINAREC = mongoengine.FloatField(max_length=30)
    SUMFINAFLOWIN = mongoengine.FloatField(max_length=30)
    REPAYDEBTPAY = mongoengine.FloatField(max_length=30)
    DIVIPROFITORINTPAY = mongoengine.FloatField(max_length=30)
    OTHERFINAPAY = mongoengine.FloatField(max_length=30)
    SUMFINAFLOWOUT = mongoengine.FloatField(max_length=30)
    NETFINACASHFLOW = mongoengine.FloatField(max_length=30)
    EFFECTEXCHANGERATE = mongoengine.FloatField(max_length=30)
    NICASHEQUI = mongoengine.FloatField(max_length=30)
    CASHEQUIBEGINNING = mongoengine.FloatField(max_length=30)
    CASHEQUIENDING = mongoengine.FloatField(max_length=30)
    SALEGOODSSERVICEREC_YOY = mongoengine.FloatField(max_length=30)
    TAXRETURNREC_YOY = mongoengine.FloatField(max_length=30)
    OTHEROPERATEREC_YOY = mongoengine.FloatField(max_length=30)
    SUMOPERATEFLOWIN_YOY = mongoengine.FloatField(max_length=30)
    BUYGOODSSERVICEPAY_YOY = mongoengine.FloatField(max_length=30)
    EMPLOYEEPAY_YOY = mongoengine.FloatField(max_length=30)
    TAXPAY_YOY = mongoengine.FloatField(max_length=30)
    OTHEROPERATEPAY_YOY = mongoengine.FloatField(max_length=30)
    SUMOPERATEFLOWOUT_YOY = mongoengine.FloatField(max_length=30)
    NETOPERATECASHFLOW_YOY = mongoengine.FloatField(max_length=30)
    DISPOSALINVREC_YOY = mongoengine.FloatField(max_length=30)
    INVINCOMEREC_YOY = mongoengine.FloatField(max_length=30)
    DISPFILASSETREC_YOY = mongoengine.FloatField(max_length=30)
    OTHERINVREC_YOY = mongoengine.FloatField(max_length=30)
    SUMINVFLOWIN_YOY = mongoengine.FloatField(max_length=30)
    BUYFILASSETPAY_YOY = mongoengine.FloatField(max_length=30)
    INVPAY_YOY = mongoengine.FloatField(max_length=30)
    OTHERINVPAY_YOY = mongoengine.FloatField(max_length=30)
    SUMINVFLOWOUT_YOY = mongoengine.FloatField(max_length=30)
    NETINVCASHFLOW_YOY = mongoengine.FloatField(max_length=30)
    LOANREC_YOY = mongoengine.FloatField(max_length=30)
    OTHERFINAREC_YOY = mongoengine.FloatField(max_length=30)
    SUMFINAFLOWIN_YOY = mongoengine.FloatField(max_length=30)
    REPAYDEBTPAY_YOY = mongoengine.FloatField(max_length=30)
    DIVIPROFITORINTPAY_YOY = mongoengine.FloatField(max_length=30)
    OTHERFINAPAY_YOY = mongoengine.FloatField(max_length=30)
    SUMFINAFLOWOUT_YOY = mongoengine.FloatField(max_length=30)
    NETFINACASHFLOW_YOY = mongoengine.FloatField(max_length=30)
    EFFECTEXCHANGERATE_YOY = mongoengine.FloatField(max_length=30)
    NICASHEQUI_YOY = mongoengine.FloatField(max_length=30)
    CASHEQUIBEGINNING_YOY = mongoengine.FloatField(max_length=30)
    CASHEQUIENDING_YOY = mongoengine.FloatField(max_length=30)

class zcfzb(mongoengine.Document):
    REPORTDATE = mongoengine.StringField(max_length=30)
    STOCKNAME = mongoengine.StringField(max_length=30)
    MONETARYFUND = mongoengine.FloatField(max_length=30)
    ACCOUNTREC = mongoengine.FloatField(max_length=30)
    ADVANCEPAY = mongoengine.FloatField(max_length=30)
    OTHERREC = mongoengine.FloatField(max_length=30)
    INVENTORY = mongoengine.FloatField(max_length=30)
    OTHERLASSET = mongoengine.FloatField(max_length=30)
    SUMLASSET = mongoengine.FloatField(max_length=30)
    LOANADVANCES = mongoengine.FloatField(max_length=30)
    LTEQUITYINV = mongoengine.FloatField(max_length=30)
    ESTATEINVEST = mongoengine.FloatField(max_length=30)
    FIXEDASSET = mongoengine.FloatField(max_length=30)
    CONSTRUCTIONPROGRESS = mongoengine.FloatField(max_length=30)
    INTANGIBLEASSET = mongoengine.FloatField(max_length=30)
    DEVELOPEXP = mongoengine.FloatField(max_length=30)
    GOODWILL = mongoengine.FloatField(max_length=30)
    LTDEFERASSET = mongoengine.FloatField(max_length=30)
    DEFERINCOMETAXASSET = mongoengine.FloatField(max_length=30)
    OTHERNONLASSET = mongoengine.FloatField(max_length=30)
    SALEGOODSSERVICEREC = mongoengine.FloatField(max_length=30)
    SUMNONLASSET = mongoengine.FloatField(max_length=30)
    STBORROW = mongoengine.FloatField(max_length=30)
    BILLPAY = mongoengine.FloatField(max_length=30)
    ACCOUNTPAY = mongoengine.FloatField(max_length=30)
    ADVANCERECEIVE = mongoengine.FloatField(max_length=30)
    SALARYPAY = mongoengine.FloatField(max_length=30)
    TAXPAY = mongoengine.FloatField(max_length=30)
    INTERESTPAY = mongoengine.FloatField(max_length=30)
    OTHERPAY = mongoengine.FloatField(max_length=30)
    NONLLIABONEYEAR = mongoengine.FloatField(max_length=30)
    SUMLLIAB = mongoengine.FloatField(max_length=30)
    LTBORROW = mongoengine.FloatField(max_length=30)
    LTACCOUNTPAY = mongoengine.FloatField(max_length=30)
    DEFERINCOME = mongoengine.FloatField(max_length=30)
    DEFERINCOMETAXLIAB = mongoengine.FloatField(max_length=30)
    SUMNONLLIAB = mongoengine.FloatField(max_length=30)
    SUMLIAB = mongoengine.FloatField(max_length=30)
    SHARECAPITAL = mongoengine.FloatField(max_length=30)
    CAPITALRESERVE = mongoengine.FloatField(max_length=30)
    INVENTORYSHARE = mongoengine.FloatField(max_length=30)
    SPECIALRESERVE = mongoengine.FloatField(max_length=30)
    RETAINEDEARNING = mongoengine.FloatField(max_length=30)
    SUMPARENTEQUITY = mongoengine.FloatField(max_length=30)
    MINORITYEQUITY = mongoengine.FloatField(max_length=30)
    SUMSHEQUITY = mongoengine.FloatField(max_length=30)
    SUMLIABSHEQUITY = mongoengine.FloatField(max_length=30)
    TOTAL_OTHER_RECE = mongoengine.FloatField(max_length=30)
    ACCOUNTBILLPAY = mongoengine.FloatField(max_length=30)
    MONETARYFUND_YOY = mongoengine.FloatField(max_length=30)
    ACCOUNTREC_YOY = mongoengine.FloatField(max_length=30)
    ADVANCEPAY_YOY = mongoengine.FloatField(max_length=30)
    OTHERREC_YOY = mongoengine.FloatField(max_length=30)
    INVENTORY_YOY = mongoengine.FloatField(max_length=30)
    OTHERLASSET_YOY = mongoengine.FloatField(max_length=30)
    SUMLASSET_YOY = mongoengine.FloatField(max_length=30)
    LOANADVANCES_YOY = mongoengine.FloatField(max_length=30)

    LTEQUITYINV_YOY = mongoengine.FloatField(max_length=30)
    ESTATEINVEST_YOY = mongoengine.FloatField(max_length=30)
    FIXEDASSET_YOY = mongoengine.FloatField(max_length=30)
    CONSTRUCTIONPROGRESS_YOY = mongoengine.FloatField(max_length=30)
    INTANGIBLEASSET_YOY = mongoengine.FloatField(max_length=30)
    DEVELOPEXP_YOY = mongoengine.FloatField(max_length=30)
    GOODWILL_YOY = mongoengine.FloatField(max_length=30)
    LTDEFERASSET_YOY = mongoengine.FloatField(max_length=30)
    DEFERINCOMETAXASSET_YOY = mongoengine.FloatField(max_length=30)
    OTHERNONLASSET_YOY = mongoengine.FloatField(max_length=30)
    SUMNONLASSET_YOY = mongoengine.FloatField(max_length=30)
    SUMASSET_YOY = mongoengine.FloatField(max_length=30)
    STBORROW_YOY = mongoengine.FloatField(max_length=30)
    BILLPAY_YOY = mongoengine.FloatField(max_length=30)
    ACCOUNTPAY_YOY = mongoengine.FloatField(max_length=30)
    ADVANCERECEIVE_YOY = mongoengine.FloatField(max_length=30)
    SALARYPAY_YOY = mongoengine.FloatField(max_length=30)
    TAXPAY_YOY = mongoengine.FloatField(max_length=30)
    INTERESTPAY_YOY = mongoengine.FloatField(max_length=30)
    OTHERPAY_YOY = mongoengine.FloatField(max_length=30)
    NONLLIABONEYEAR_YOY = mongoengine.FloatField(max_length=30)
    SUMLLIAB_YOY = mongoengine.FloatField(max_length=30)
    LTBORROW_YOY = mongoengine.FloatField(max_length=30)
    LTACCOUNTPAY_YOY = mongoengine.FloatField(max_length=30)
    DEFERINCOME_YOY = mongoengine.FloatField(max_length=30)
    DEFERINCOMETAXLIAB_YOY = mongoengine.FloatField(max_length=30)
    SUMNONLLIAB_YOY = mongoengine.FloatField(max_length=30)
    SUMLIAB_YOY = mongoengine.FloatField(max_length=30)
    SHARECAPITAL_YOY = mongoengine.FloatField(max_length=30)
    CAPITALRESERVE_YOY = mongoengine.FloatField(max_length=30)
    INVENTORYSHARE_YOY = mongoengine.FloatField(max_length=30)
    SPECIALRESERVE_YOY = mongoengine.FloatField(max_length=30)
    RETAINEDEARNING_YOY = mongoengine.FloatField(max_length=30)
    SUMPARENTEQUITY_YOY = mongoengine.FloatField(max_length=30)
    MINORITYEQUITY_YOY = mongoengine.FloatField(max_length=30)
    SUMSHEQUITY_YOY = mongoengine.FloatField(max_length=30)
    SUMLIABSHEQUITY_YOY = mongoengine.FloatField(max_length=30)

class yydy(mongoengine.Document):
    ch = mongoengine.StringField(max_length=30)
    en = mongoengine.StringField(max_length=30)
    dbname = mongoengine.StringField(max_length=30)







